language: python

before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b
    - . /home/travis/miniconda3/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda config --add channels r
    - conda create --yes -n test_env
    - conda activate test_env
    - conda install --yes python=3.8.5
    - conda install --yes pycodestyle
    - pip install -r requirements.txt

script:
    - pycodestyle utils.py
    - pycodestyle test_utils.py
    - pycodestyle get_diffusion.py
    - pycodestyle convert_ND_to_TIF.py
    - python test_utils.py


